<?php

// TODO: check if we can achieve this with content type settings instead.
function ezh_node_view($node, $build_mode = 'full') {
  if ($node->type == 'srecipe') {
    $node->readmore = true;
  }
}

function ezh_filter_info() {
  $filters = array();
  $filters['ezh_local_links'] = array(
    'title' => t('Convert local URLs to named links'),
    'description' => t('URLs which refer to local resources will be replaced by named links to those resources.'),
    'process callback' => 'ezh_local_links_process',
  );
  return $filters;
}

function ezh_local_links_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  global $base_url;

  // Look for local URLs by $base_url
  // 1) Remove http[s]:// from $base_url
  $base = preg_replace("`^https?://`", '', $base_url);

  // 2) Search for URLs that start with this $base
  $text = ' '. $text .' ';
  $text = preg_replace_callback("`(<p>|<li>|<br\s*/?>|[ \n\r\t\(])((http://|https://)($base/)([a-zA-Z0-9@:%_+*~#?&=.,/;-]*[a-zA-Z0-9@:%_+*~#&=/;-]))([.,?!]*?)(?=(</p>|</li>|<br\s*/?>|[ \n\r\t\)]))`i", '_ezh_url_parse_full_links', $text);

  return $text;
}

function _ezh_url_parse_full_links($match) {
  $match[2] = decode_entities($match[2]);
  $url = check_url(decode_entities($match[2]));
  $path = drupal_get_normal_path($match[5]);

  if (preg_match("#^node/([0-9]+)#", $path, $m)) {
    // It would be cool to do a node_load() here, but that has the side
    // effect of running all the filters for that node, which includes
    // this filter right here. Infinite recursion results. Barf-o-rama.
    $caption = db_query('SELECT title FROM {node} WHERE nid = :nid', array(':nid' => $m[1]))->fetchField();
    return $match[1] .'<a href="'. $url .'" title="'. $match[5] .'">'. $caption .'</a>'. $match[6];
  }
  else {
    return $match[0];
  }
}

function ezh_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  if ($user->uid == 1) {
    $form['#attributes']['class'][] = 'show-format-widgets';
  }
}

/**
 * Implements hook_menu()
 */
function ezh_menu() {
  $items = array();
  $items['join-mailing-list'] = array(
    'page callback' => 'ezh_mailinglist_form',
    'title' => t('Join the mailing list'),
    'type' => MENU_NORMAL_ITEM,
    'access arguments' => array('access content'),
  );
  return $items;
}

function ezh_mailinglist_form() {
  module_load_include('inc', 'contact', 'contact.pages');
  $form = drupal_get_form('contact_site_form');

  $form['header'] = array(
    '#weight' => -10,
    '#markup' => "<div>Would you like to receive a weekly update telling of new recipes and news of our project? <br> Just let us know your name and where you live (city, state, and country), and we'll introduce you to the group.</div>",
  );

  $form['subject']['#value'] = 'Somebody wants to join the mailing list';
  $form['subject']['#default_value'] = 'Somebody wants to join the mailing list';

  $form['#attributes']['class'][] = 'mailing-list-form';

  $form['message']['#title'] = 'Geographic location';
  $form['message']['#value'] = "City:\nState:\nCountry:";

  return $form;
}
