<?php

function _patdb_setup_pathauto() {
  // Set up pathauto patterns
  variable_set('pathauto_taxonomy_term_committees_pattern', 'committee/[term:name]');
  variable_set('pathauto_taxonomy_term_roles_pattern', 'role/[term:name]');
  variable_set('pathauto_node_cluster_pattern', 'cluster/[node:title]');
  variable_set('pathauto_node_member_pattern', 'member/[node:title]');
  variable_set('pathauto_node_school_pattern', 'school/[node:title]');

  // Ensure they're all up to date!

}

function _patdb_setup_content() {
  foreach (array('cluster', 'member', 'school') as $type) {
    variable_set("node_options_$type", array('status', 'revision'));
  }
}

function _patdb_setup_views() {
  // move views blocks to content area
  // (assuming they exist already)
  // FIXME: This fails silently if the blocks do not exist.
  // 1) get the weight of the main content
  $main_weight = db_select('block')
    ->fields('block', array('weight'))
    ->condition('module', 'system')
    ->condition('delta', 'main')
    ->execute()->fetchField();

  // 2) add the views blocks to the content area below the content
  db_update('block')
    ->fields(array(
      'region' => 'content',
      'status' => 1,
      'weight' => $main_weight + 1, ))
    ->condition('module', 'views')
    ->condition('delta', array('members_by_school-block_1', 'schools_by_cluster-block_1'), 'IN')
    ->execute();
}
