<?php

function patdb_reports_menu() {
  $items = array();
  $items['reports/all-reps-by-cluster.pdf'] = array(
    'title' => 'All Reps by Cluster (PDF)',
    'page callback' => 'patdb_reports_reps_by_cluster',
    'page arguments' => array(1, 'I'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
* @brief Ensure TCPDF and rep_report_pdf are both present
*
* @return No return value.
*/
function patdb_reports_require_tcpdf() {
  if (function_exists('libraries_get_path')) {
    $path = libraries_get_path('tcpdf');
  }
  else {
    $path = DRUPAL_ROOT .'/sites/all/libraries/tcpdf';
  }

  require_once $path .'/tcpdf.php';
  require_once 'rep_report.inc';
}

/**
* @brief Build the query object for the "building reps by cluster" report
*        The query selects reps, ordered by
*        cluster and school, with "Head Rep" members listed first.
*
* @return No return value.
*/
function patdb_reports_reps_query() {
  // Get building rep tid
  $building_rep = array_pop(taxonomy_get_term_by_name('Building Rep'));
  $head_rep = array_pop(taxonomy_get_term_by_name('Head Rep'));

  $tid_order = ($head_rep->tid > $building_rep->tid) ? 'DESC' : 'ASC';

  $q = db_select('node', 'n');
  $q->join('field_data_field_school', 's', "n.nid = s.entity_id AND s.entity_type = 'node' AND s.deleted = 0");
  $q->join('field_data_field_cluster', 'c', "s.field_school_nid = c.entity_id AND c.entity_type = 'node' AND c.deleted = 0");
  $q->join('field_data_field_roles', 'r', "n.nid = r.entity_id AND r.entity_type = 'node' AND r.deleted = 0");
  $q->join('field_data_field_home_phone', 'p', "n.nid = p.entity_id AND p.entity_type = 'node' AND p.deleted = 0");
  $q->join('field_data_field_email', 'e', "n.nid = e.entity_id AND e.entity_type = 'node' AND e.deleted = 0");
  $q->addField('n', 'nid', 'nid');
  $q->addField('n', 'title', 'title');
  $q->addField('p', 'field_home_phone_value', 'home_phone');
  $q->addField('e', 'field_email_email', 'email');
  $q->addField('s', 'field_school_nid', 'school_nid');
  $q->addField('c', 'field_cluster_nid', 'cluster_nid');
  $q->condition('n.status', 1)
    ->condition('n.type', 'member')
    ->condition('s.field_school_nid', 0, '>') // omit members with no school
    ->condition('c.field_cluster_nid', 0, '>') // omit schools with no cluster
    ->condition('r.field_roles_tid', array($building_rep->tid, $head_rep->tid), 'IN')
    ->orderBy('cluster_nid')
    ->orderBy('school_nid')
    ->orderBy('r.field_roles_tid', $tid_order)
    ->orderBy('n.title');

  return $q;
}

/**
* @brief Create the "building reps by cluster" report, using the
*        rep_report_pdf class to do the PDF layout.
*
* @param $filename Name of output filename
* @param $mode TCPDF output mode -- 'F' for local file, 'I' for browser
*
* @return No return value.
*/
function patdb_reports_reps_by_cluster($filename, $mode = 'I') {
  $q = patdb_reports_reps_query();
  $result = $q->execute();

  // Query results will contain duplicates because we are matching
  // two "role" tids. So we save members as we iterate, indexed by
  // nid to eliminate dupes. A helper function lets us easily
  // output & clear the $members array whenever we reach the end
  // of a school or cluster.
  patdb_reports_require_tcpdf();
  $pdf = new rep_report_pdf();
  $school = $cluster = NULL;
  $members = array();
  while ($member = $result->fetchObject()) {
    if (is_null($cluster) || $member->cluster_nid != $cluster->nid) {
      _patdb_reports_rbc_add_members($pdf, $members);
      $cluster = node_load($member->cluster_nid);
      $director = node_load($cluster->field_director[$cluster->language][0]['nid']);
      $director = $director ? $director->title : '[none]';
      $pdf->newCluster($cluster->title, $director);
    }
    if (is_null($school) || $member->school_nid != $school->nid) {
      _patdb_reports_rbc_add_members($pdf, $members);
      $school = node_load($member->school_nid);
      $phone = $school->field_office_phone[$school->language][0]['value'];
      $phone = theme('nice_phone_number', array('number' => $phone));
      $pdf->newSchool($school->title, $phone);
    }
    $members['nid_'. $member->nid] = $member;
  }
  _patdb_reports_rbc_add_members($pdf, $members);

  $pdf->Output($filename, $mode);
}


/**
* @brief Add $members to $pdf and clear $members.
*
* @param $pdf A rep_report_pdf object to which to add the members
* @param $members An array of $member objects containing these properties:
*     $member->home_phone,
*     $member->email,
*     $member->title
*
* @return No return value.
*/
function _patdb_reports_rbc_add_members(&$pdf, &$members) {
  if (count($members)) {
    foreach ($members as $member) {
      $phone = theme('nice_phone_number', array('number' => $member->home_phone));
      $pdf->newMember($member->title, $phone, $member->email);
    }
    $members = array();
  }
}
